packages:
  - 'bundles/*'
  - 'components/*'
  - 'demo/**'
  - 'editor'
  - 'engine'
  - 'interactions/*'
  - 'interactions/external/*'
  - 'interactions/particles/*'
  - 'move/*'
  - 'paths/*'
  - 'plugins/*'
  - 'plugins/easings/*'
  - 'presets/*'
  - 'shapes/*'
  - 'templates/*'
  - 'updaters/*'
  - 'utils/*'
  - 'utils/cli/files/create-preset/js'
  - 'utils/cli/files/create-preset/ts'
  - 'websites/*'
